# HATEOAS API
# go_integro_sample_api2:
#     resource: "@HateoasIncExampleBundle/Rest2/Controller/"
#     prefix: /api/v1

# HATEOAS bundle
go_integro_hateoas:
    resource: "@GoIntegroHateoasBundle/Resources/config/routing.yml"
    prefix: /api/v1
